# Generated by PCB_Quality_Inspector.ipynb; do not edit by hand.
"""Local six-class PCB inspection app using the fixed Enhanced Trial 044 model."""

from __future__ import annotations

import hashlib
import io
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st
import torch
from PIL import Image
from ultralytics import YOLO


PACKAGE = Path(__file__).resolve().parent
sys.path.insert(0, str(PACKAGE / "model_code"))

from inspector_core import (
    CLASS_COLOURS,
    EXPECTED_CLASSES,
    INFERENCE_SETTINGS,
    CheckpointVerificationError,
    UploadValidationError,
    assert_class_mapping,
    detections_to_csv,
    load_image_bytes,
    normalise_detections,
    render_annotated_png,
    summarise_detections,
    verify_trial044_checkpoint,
)


st.set_page_config(
    page_title="PCB Quality Inspector — Enhanced YOLOv8n",
    page_icon="🔬",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown(
    """
    <style>
    :root {
      --navy: #102a43;
      --navy-soft: #243b53;
      --green: #087f5b;
      --green-soft: #e6fcf5;
      --blue-soft: #e7f5ff;
      --surface: #ffffff;
      --canvas: #f4f7fa;
      --line: #d9e2ec;
      --text: #102a43;
      --muted: #627d98;
      --danger: #b42318;
      --danger-soft: #fef3f2;
      --warning: #9a6700;
      --warning-soft: #fff8c5;
    }
    .stApp { background: var(--canvas); color: var(--text); }
    [data-testid="stHeader"] { background: transparent; }
    [data-testid="stSidebar"] { background: #eef3f7; border-right: 1px solid var(--line); color: var(--text); }
    [data-testid="stSidebar"] h1,
    [data-testid="stSidebar"] h2,
    [data-testid="stSidebar"] h3,
    [data-testid="stSidebar"] label,
    [data-testid="stSidebar"] p,
    [data-testid="stSidebar"] span { color: var(--text); }
    [data-testid="stSidebar"] code { background: #d9e2ec; color: #0b4f71; }
    .block-container { max-width: 1180px; padding-top: 2rem; padding-bottom: 3rem; }
    .hero {
      background: linear-gradient(125deg, var(--navy), var(--navy-soft));
      border-radius: 18px;
      padding: 1.55rem 1.75rem;
      margin-bottom: 1.25rem;
      color: white;
      box-shadow: 0 10px 28px rgba(16, 42, 67, .14);
    }
    .hero h1 { margin: 0 0 .35rem; font-size: clamp(1.65rem, 3vw, 2.45rem); line-height: 1.15; }
    .hero p { margin: 0; color: #d9e2ec; max-width: 760px; }
    .eyebrow { text-transform: uppercase; letter-spacing: .09em; font-size: .75rem; font-weight: 700; color: #9fb3c8; }
    .status-banner { border-radius: 12px; padding: .9rem 1rem; margin: .75rem 0 1rem; font-weight: 700; }
    .status-empty { background: var(--blue-soft); border: 1px solid #90cdf4; color: #0b4f71; }
    .status-clear { background: var(--green-soft); border: 1px solid #63e6be; color: #065f46; }
    .status-review { background: var(--warning-soft); border: 1px solid #f2cc60; color: #7a4d00; }
    .status-error { background: var(--danger-soft); border: 1px solid #fda29b; color: var(--danger); }
    .badge { display: inline-block; border-radius: 999px; padding: .28rem .68rem; font-size: .8rem; font-weight: 700; }
    .badge-ready { background: var(--green-soft); color: #065f46; border: 1px solid #63e6be; }
    .badge-class { background: #eaf0f6; color: var(--navy); border: 1px solid var(--line); margin: .15rem .25rem .15rem 0; }
    .class-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: .7rem; }
    .class-count { background: var(--surface); border: 1px solid var(--line); border-left-width: 4px; border-radius: 12px; padding: .7rem .85rem; }
    .class-count-label { color: var(--muted); font-size: .78rem; font-weight: 700; line-height: 1.2; }
    .class-count-value { color: var(--text); font-size: 1.45rem; font-weight: 750; line-height: 1.35; }
    .panel { background: var(--surface); border: 1px solid var(--line); border-radius: 14px; padding: 1rem; }
    div[data-testid="stMetric"] { background: var(--surface); border: 1px solid var(--line); border-radius: 12px; padding: .85rem 1rem; }
    div[data-testid="stFileUploader"] { background: var(--surface); border: 1px solid var(--line); border-radius: 14px; padding: .35rem .65rem; }
    [data-testid="stFileUploaderDropzone"] { background: var(--surface); border-color: #9fb3c8; }
    [data-testid="stFileUploaderDropzone"] p,
    [data-testid="stFileUploaderDropzone"] span,
    [data-testid="stFileUploaderDropzone"] small { color: var(--text); }
    [data-testid="stFileUploaderDropzone"] button { background: #eaf0f6; color: var(--navy); border: 1px solid #bcccdc; }
    .stButton > button { background: var(--green); color: white; border: 0; border-radius: 10px; font-weight: 700; min-height: 2.8rem; }
    .stButton > button:hover, .stButton > button:focus { background: #066a4c; color: white; border: 0; }
    @media (max-width: 720px) {
      .block-container { padding: 1rem .8rem 2rem; }
      .hero { padding: 1.2rem; border-radius: 14px; }
      .class-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
    }
    </style>
    """,
    unsafe_allow_html=True,
)


def selected_device():
    return 0 if torch.cuda.is_available() else "cpu"


@st.cache_resource(show_spinner="Verifying and loading Trial 044...")
def load_verified_model():
    checkpoint = verify_trial044_checkpoint(PACKAGE)
    model = YOLO(str(checkpoint))
    assert_class_mapping(model.names)
    return model


def class_badges():
    labels = "".join(
        f'<span class="badge badge-class" style="border-color:{CLASS_COLOURS[name]}; color:{CLASS_COLOURS[name]}">{name.replace("_", " ")}</span>'
        for name in EXPECTED_CLASSES.values()
    )
    st.markdown(labels, unsafe_allow_html=True)


def class_count_cards(summary):
    cards = "".join(
        (
            f'<div class="class-count" style="border-left-color:{CLASS_COLOURS[name]}">'
            f'<div class="class-count-label">{name.replace("_", " ").title()}</div>'
            f'<div class="class-count-value">{summary["per_class_counts"].get(name, 0)}</div>'
            "</div>"
        )
        for name in EXPECTED_CLASSES.values()
    )
    st.markdown(f'<div class="class-grid">{cards}</div>', unsafe_allow_html=True)


def status_banner(message, kind):
    st.markdown(
        f'<div class="status-banner status-{kind}" role="status">{message}</div>',
        unsafe_allow_html=True,
    )


def readable_rows(rows):
    table = pd.DataFrame(rows)
    if table.empty:
        return table
    table["class"] = table.pop("class_name").str.replace("_", " ")
    table["confidence"] = table["confidence"].map(lambda value: f"{value:.1%}")
    for column in ("x1", "y1", "x2", "y2", "width", "height"):
        table[column] = table[column].round(1)
    return table[["class", "confidence", "x1", "y1", "x2", "y2", "width", "height"]]


st.markdown(
    """
    <section class="hero">
      <div class="eyebrow">Local FYP inspection workspace</div>
      <h1>PCB Quality Inspector — Enhanced YOLOv8n</h1>
      <p>Upload one PCB image, choose a confidence threshold, and inspect the six-class Trial 044 prediction. Images stay in this local session.</p>
    </section>
    """,
    unsafe_allow_html=True,
)

with st.sidebar:
    st.subheader("Inspection settings")
    try:
        verified_checkpoint = verify_trial044_checkpoint(PACKAGE)
        st.markdown('<span class="badge badge-ready">Trial 044 verified</span>', unsafe_allow_html=True)
        checkpoint_caption = f"Checkpoint: `{verified_checkpoint.name}`"
    except CheckpointVerificationError as error:
        verified_checkpoint = None
        checkpoint_caption = str(error)
        st.error("Trial 044 is not ready")
    st.caption(checkpoint_caption)
    device_label = torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU fallback"
    st.caption(f"Device: **{device_label}**")
    confidence = st.slider(
        "Confidence threshold",
        min_value=0.05,
        max_value=0.95,
        value=0.25,
        step=0.05,
        help="Lower values show more possible defects; higher values retain stronger detections.",
    )
    st.divider()
    st.caption("Fixed inference: 1024 px · IoU 0.70 · max 300 detections")
    st.caption("Validation evidence only. This tool does not certify a PCB as passed.")

left, right = st.columns([1.45, 1], gap="large")
with left:
    st.subheader("Inspect one PCB image")
    uploaded = st.file_uploader(
        "Upload a PCB image",
        type=["jpg", "jpeg", "png"],
        accept_multiple_files=False,
        help="JPG, JPEG, or PNG; maximum 10 MB and 20 megapixels.",
    )
with right:
    st.subheader("Supported defect classes")
    class_badges()
    st.caption("All six model classes remain visible; predictions are not filtered to short circuits.")

upload_digest = hashlib.sha256(uploaded.getvalue()).hexdigest() if uploaded else None
if st.session_state.get("inspection", {}).get("upload_digest") != upload_digest:
    st.session_state.pop("inspection", None)

inspect_clicked = st.button(
    "Inspect PCB",
    type="primary",
    width="stretch",
    disabled=uploaded is None or verified_checkpoint is None,
)

if uploaded is None:
    status_banner("Upload a JPG or PNG image to begin.", "empty")
elif inspect_clicked:
    try:
        image = load_image_bytes(uploaded.getvalue())
        with st.spinner("Inspecting PCB with Enhanced Trial 044..."):
            model = load_verified_model()
            started = time.perf_counter()
            results = model.predict(
                source=np.asarray(image),
                conf=confidence,
                device=selected_device(),
                verbose=False,
                **INFERENCE_SETTINGS,
            )
            elapsed_ms = (time.perf_counter() - started) * 1000
        rows = normalise_detections(results[0], model.names)
        summary = summarise_detections(rows)
        st.session_state["inspection"] = {
            "upload_digest": upload_digest,
            "confidence": confidence,
            "image_png": render_annotated_png(image, []),
            "annotated_png": render_annotated_png(image, rows),
            "csv": detections_to_csv(rows),
            "rows": rows,
            "summary": summary,
            "elapsed_ms": elapsed_ms,
        }
    except UploadValidationError as error:
        st.session_state["inspection"] = {"upload_digest": upload_digest, "error": str(error)}
    except Exception as error:
        st.session_state["inspection"] = {
            "upload_digest": upload_digest,
            "error": f"{type(error).__name__}: {error}",
        }

inspection = st.session_state.get("inspection")
if inspection and inspection.get("error"):
    status_banner("Inspection could not be completed", "error")
    st.error(inspection["error"])
elif inspection:
    rows = inspection["rows"]
    summary = inspection["summary"]
    if rows:
        status_banner("Defects detected — review required", "review")
    else:
        status_banner("No defects detected", "clear")
        st.caption("No boxes met the selected threshold. This is not a quality-control pass decision.")

    metrics = st.columns(4)
    metrics[0].metric("Total detections", summary["total_detections"])
    metrics[1].metric("Classes found", summary["classes_found"])
    metrics[2].metric("Mean confidence", f"{summary['mean_confidence']:.1%}")
    metrics[3].metric("Inference time", f"{inspection['elapsed_ms']:.0f} ms")

    top_defect = summary["top_defect"]
    if top_defect:
        st.markdown(
            f'**Top defect:** <span class="badge badge-class" style="border-color:{CLASS_COLOURS[top_defect]}; color:{CLASS_COLOURS[top_defect]}">{top_defect.replace("_", " ")}</span>',
            unsafe_allow_html=True,
        )

    result_tab, original_tab = st.tabs(["Detection result", "Original image"])
    with result_tab:
        st.image(inspection["annotated_png"], caption="Enhanced Trial 044 detections", width="stretch")
    with original_tab:
        st.image(inspection["image_png"], caption="Untouched uploaded image", width="stretch")

    with st.expander("Compare detection and original side by side"):
        comparison_left, comparison_right = st.columns(2)
        comparison_left.image(inspection["annotated_png"], caption="Detection result", width="stretch")
        comparison_right.image(inspection["image_png"], caption="Original image", width="stretch")

    st.subheader("Defect counts")
    class_count_cards(summary)

    st.subheader("Detection details")
    if rows:
        st.dataframe(readable_rows(rows), width="stretch", hide_index=True)
    else:
        st.info("No detection rows are available at this threshold.")

    download_left, download_right = st.columns(2)
    download_left.download_button(
        "Download annotated PNG",
        data=inspection["annotated_png"],
        file_name="pcb_detection_trial044.png",
        mime="image/png",
        width="stretch",
    )
    download_right.download_button(
        "Download detections CSV",
        data=inspection["csv"],
        file_name="pcb_detection_trial044.csv",
        mime="text/csv",
        width="stretch",
    )
    st.caption(f"Inference used confidence {inspection['confidence']:.2f}. Move the slider and click Inspect PCB to run again.")
elif uploaded is not None:
    status_banner("Image ready — click Inspect PCB to run the model.", "empty")
